### ISSUE TITLE
Default dirs?

### ISSUE THREAD

**Issue by WWalshC4** [control4/drivers-driverpackager#4]
Set default dirs for srcdir and destdir to ./ and ./../ ?

**Comment by FDrazicC4** [comment]
I agree for srcdir. I do not remember calling Driver Packager with a srcdir different than the current directory.
For destdir, I think current directory should also be used. I think that an improvement could be to specify the default output directory in the manifest file (e.g. an attribute of the Driver node), but this is maybe when we switch to 'DriverPackager V2' and JSON manifest files.

Since srcdir and destdir are positional arguments, I think that both must be provided or none of them, to prevent ambiguity:

```
# Is '.' srcdir or destdir?
driverpackager.py -v . driver.c4zproj
````

**Comment by WWalshC4** [comment]
Agreed on the 1 or 3 args; we could (should) potentially also add flag calls to support this so that we're not relying on positional args:
driverpackager.py --srcdir ./ --destdir ./../ driver.c4zproj
I like the idea of having the manifest specify an output dir relative to the c4zproj.  I'd then need to see whether we could omit the srcdir and destdir entirely; the c4zproj specifies the sourcedir effectively by itself, and at that point the srcdir would only be needed if you weren't running against a c4zproj but just against a directory, which I think I would be happy making an unsupported use case.

**Comment by sethpjohnson** [comment]
I'd much rather have the flag support over the positional args. I don't think you need any defaults but if you did those aren't bad.
